language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
    - master
    - develop
script:
  - yarn run lint
  - yarn test
notifications:
  - email: false
install:
  - yarn install
cache:
  yarn: true
  directories:
    - "node_modules"
